import { NextResponse } from "next/server"

const crewData = {
  flightCrew: [
    {
      id: "FC001",
      name: "Captain John Smith",
      age: 45,
      gender: "Male",
      nationality: "Turkish",
      languages: ["Turkish", "English", "German"],
      seniority: "Senior",
      vehicleRestriction: "Boeing 777",
      allowedRange: 15000,
      position: "Captain",
    },
    {
      id: "FC002",
      name: "First Officer Sarah Johnson",
      age: 32,
      gender: "Female",
      nationality: "American",
      languages: ["English", "Spanish"],
      seniority: "Junior",
      vehicleRestriction: "Boeing 777",
      allowedRange: 12000,
      position: "First Officer",
    },
    {
      id: "FC003",
      name: "Captain Ahmed Yilmaz",
      age: 52,
      gender: "Male",
      nationality: "Turkish",
      languages: ["Turkish", "English", "Arabic"],
      seniority: "Senior",
      vehicleRestriction: "Airbus A320",
      allowedRange: 8000,
      position: "Captain",
    },
    {
      id: "FC004",
      name: "First Officer Emma Wilson",
      age: 29,
      gender: "Female",
      nationality: "British",
      languages: ["English", "French"],
      seniority: "Junior",
      vehicleRestriction: "Airbus A320",
      allowedRange: 6000,
      position: "First Officer",
    },
    {
      id: "FC005",
      name: "Trainee Pilot Mark Davis",
      age: 25,
      gender: "Male",
      nationality: "Canadian",
      languages: ["English"],
      seniority: "Trainee",
      vehicleRestriction: "Boeing 737",
      allowedRange: 4000,
      position: "Trainee Pilot",
    },
  ],
  cabinCrew: [
    {
      id: "CC001",
      name: "Maria Rodriguez",
      age: 35,
      gender: "Female",
      nationality: "Spanish",
      languages: ["Spanish", "English", "Turkish"],
      type: "Chief",
      vehicleRestrictions: ["Boeing 777", "Airbus A320"],
      position: "Chief Flight Attendant",
    },
    {
      id: "CC002",
      name: "Ahmed Hassan",
      age: 28,
      gender: "Male",
      nationality: "Turkish",
      languages: ["Turkish", "Arabic", "English"],
      type: "Regular",
      vehicleRestrictions: ["Boeing 777", "Airbus A320"],
      position: "Flight Attendant",
    },
    {
      id: "CC003",
      name: "Chef Pierre Dubois",
      age: 42,
      gender: "Male",
      nationality: "French",
      languages: ["French", "English"],
      type: "Chef",
      vehicleRestrictions: ["Boeing 777"],
      recipes: ["Coq au Vin", "Beef Bourguignon", "Ratatouille"],
      position: "Chef",
    },
    {
      id: "CC004",
      name: "Lisa Chen",
      age: 26,
      gender: "Female",
      nationality: "Chinese",
      languages: ["Chinese", "English"],
      type: "Regular",
      vehicleRestrictions: ["Boeing 777", "Airbus A320"],
      position: "Flight Attendant",
    },
    {
      id: "CC005",
      name: "Anna Kowalski",
      age: 31,
      gender: "Female",
      nationality: "Polish",
      languages: ["Polish", "English", "German"],
      type: "Chief",
      vehicleRestrictions: ["Airbus A320", "Boeing 737"],
      position: "Chief Flight Attendant",
    },
    {
      id: "CC006",
      name: "Chef Marco Rossi",
      age: 38,
      gender: "Male",
      nationality: "Italian",
      languages: ["Italian", "English"],
      type: "Chef",
      vehicleRestrictions: ["Boeing 777", "Airbus A320"],
      recipes: ["Risotto Milanese", "Osso Buco", "Tiramisu"],
      position: "Chef",
    },
    {
      id: "CC007",
      name: "Fatima Al-Zahra",
      age: 27,
      gender: "Female",
      nationality: "Moroccan",
      languages: ["Arabic", "French", "English"],
      type: "Regular",
      vehicleRestrictions: ["Boeing 777", "Airbus A320", "Boeing 737"],
      position: "Flight Attendant",
    },
    {
      id: "CC008",
      name: "James Thompson",
      age: 33,
      gender: "Male",
      nationality: "Australian",
      languages: ["English"],
      type: "Regular",
      vehicleRestrictions: ["Boeing 777", "Airbus A320"],
      position: "Flight Attendant",
    },
  ],
}

export async function GET() {
  return NextResponse.json(crewData)
}
