import { NextResponse } from "next/server"

const flightData = {
  flights: [
    {
      flightNumber: "TK1234",
      date: "2024-01-15",
      time: "14:30",
      duration: "8h 45m",
      distance: "8,000 km",
      source: {
        country: "Turkey",
        city: "Istanbul",
        airport: "Istanbul Airport",
        code: "IST",
      },
      destination: {
        country: "United States",
        city: "New York",
        airport: "John F. Kennedy International Airport",
        code: "JFK",
      },
      aircraftType: "Boeing 777-300ER",
      totalSeats: 396,
      status: "Active",
      sharedFlight: null,
    },
    {
      flightNumber: "TK5678",
      date: "2024-01-16",
      time: "10:15",
      duration: "4h 20m",
      distance: "2,500 km",
      source: {
        country: "Turkey",
        city: "Istanbul",
        airport: "Istanbul Airport",
        code: "IST",
      },
      destination: {
        country: "United Kingdom",
        city: "London",
        airport: "Heathrow Airport",
        code: "LHR",
      },
      aircraftType: "Airbus A320",
      totalSeats: 180,
      status: "Scheduled",
      sharedFlight: null,
    },
    {
      flightNumber: "TK9012",
      date: "2024-01-17",
      time: "16:45",
      duration: "3h 55m",
      distance: "2,200 km",
      source: {
        country: "Turkey",
        city: "Istanbul",
        airport: "Istanbul Airport",
        code: "IST",
      },
      destination: {
        country: "France",
        city: "Paris",
        airport: "Charles de Gaulle Airport",
        code: "CDG",
      },
      aircraftType: "Airbus A320",
      totalSeats: 180,
      status: "Scheduled",
      sharedFlight: null,
    },
    {
      flightNumber: "TK3456",
      date: "2024-01-14",
      time: "09:30",
      duration: "6h 15m",
      distance: "4,500 km",
      source: {
        country: "Turkey",
        city: "Istanbul",
        airport: "Istanbul Airport",
        code: "IST",
      },
      destination: {
        country: "Germany",
        city: "Frankfurt",
        airport: "Frankfurt Airport",
        code: "FRA",
      },
      aircraftType: "Boeing 737-800",
      totalSeats: 189,
      status: "Completed",
      sharedFlight: {
        partnerFlightNumber: "LH7890",
        partnerAirline: "Lufthansa",
      },
    },
    {
      flightNumber: "TK7890",
      date: "2024-01-18",
      time: "22:00",
      duration: "12h 30m",
      distance: "11,500 km",
      source: {
        country: "Turkey",
        city: "Istanbul",
        airport: "Istanbul Airport",
        code: "IST",
      },
      destination: {
        country: "Japan",
        city: "Tokyo",
        airport: "Narita International Airport",
        code: "NRT",
      },
      aircraftType: "Boeing 777-300ER",
      totalSeats: 396,
      status: "Scheduled",
      sharedFlight: null,
    },
    {
      flightNumber: "TK2468",
      date: "2024-01-13",
      time: "07:45",
      duration: "2h 45m",
      distance: "1,200 km",
      source: {
        country: "Turkey",
        city: "Istanbul",
        airport: "Istanbul Airport",
        code: "IST",
      },
      destination: {
        country: "Italy",
        city: "Rome",
        airport: "Leonardo da Vinci Airport",
        code: "FCO",
      },
      aircraftType: "Airbus A320",
      totalSeats: 180,
      status: "Cancelled",
      sharedFlight: null,
    },
  ],
}

export async function GET() {
  return NextResponse.json(flightData)
}
